name: Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write     # OIDC for Deno Deploy auth
      contents: read      # checkout

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: "deno install"

      - name: Build
        run: deno task build

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "random-art"
          entrypoint: ./server.production.ts
          root: .
          include: |
            deno.json
            deno.lock
            build
            package.json
            server.production.ts
            # add these if your entrypoint uses them:
            import_map.json
            app
